function NODES = nonsurround_proxy_surface_creation(NODES,proxy_layer,Nph)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%           This function construct proxy surface made of points surrounding a panel
%           empty space represents the panel'o' represents points of the proxy
%           surface.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%           here is an illustration an one-layer-thickness proxy surface
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                    top line
%                                  ooooooooooo
%                                  o         o
%                                  o         o
%                             left o  panel  o right
%                             line o  points o line
%                                  o  are    o
%                                  o  inside o
%                                  o         o
%                                  o         o
%                                  ooooooooooo
%                                   bottom line
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%           Input:
%                NODES structure, with binary tree created (tree_generation)
%                                 and x,y position coordinates stored in
%                                 each panel.              (tree_generation)
%                proxy_layer: the number of layer surrounding each panel.
%
%                According to Table 1 in the Gopal Martinsson paper,
%                choose proxy_layer = 1 for compression accuracy > 1e-5
%                choose proxy_layer = 2 for compression accuracy > 1e-10
%                choose proxy_layer = 3 for compression accuracy > mach_eps
%                
%
%
%           Outputs:
%                  NODES sturcture, with x,y position coordinates for the proxy
%                            surface for each panel computed and stored
%
%                          NODES{13,ibox}   x coordinates of proxy surface
%                          NODES{14,ibox}   y coordinates of proxy surface
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This is modified from the original proxy_surface_creation function
% by assuming that the structure is metasurface like and the tree is
% generated by making vertical cuts first then horizontal cuts.

% For levels of vertical cuts, the proxy surface becomes
%
%
%
%                                  x         x
%                                  x         x
%                                  x         x
%                                  o         o
%                                  o         o
%                             left o  panel  o right
%                             line o  points o line
%                                  o  are    o
%                                  o  inside o
%                                  o         o
%                                  o         o
%                                  x         x
%                                  x         x
%                                  x         x
%
%
% where the x represents additional points put in to make vertical lines
% sticking out, whose number is given by outnum.

% The purpose of doing that is for such a thin structure, interactions
% between different domain comes from left and right, not from top or
% bottom.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    nbox = size(NODES,2);
    xcutnum = log2(Nph);
    %ycutnum = log2(Npv);
    Nh = length(NODES{30,1}); % horizontal grid number
    Nv = length(NODES{30,2}); % vertical grid number
    h = NODES{30,1}(2) - NODES{30,1}(1);
    %outnum = 100*(ceil(log10(Nh/Nv)))*Nv; % tried 20,40
    outnum = 20*(ceil(log10(Nh/Nv)))*Nv; % length of proxy surface
    for ibox = 2: nbox % exclude root node
        level = NODES{1,ibox};
        %Nh = length(NODES{30,1}); 
        %Nv = length(NODES{30,2}); 
        
    if ibox == 2^(level-1) % the first of a level
        % orientation of horizontal axis
        if (NODES{30,1}(end) - NODES{30,1}(1)) > 0
            Oh = 1; %positive orientation
        elseif ((NODES{30,1}(end) - NODES{30,1}(1)) < 0)
            Oh = -1; %negative orientation
        else 
            Oh = 0; % will return error
        end


        % orientation of vertical axis
        if (NODES{30,2}(end) - NODES{30,2}(1)) > 0
            Ov = 1; %positive orientation
        elseif (NODES{30,2}(end) - NODES{30,2}(1)) < 0
            Ov = -1; %negative orientation
        else 
            Ov = 0; % will return error
        end


        %Oh = (NODES{30,1}(end) - NODES{30,1}(1)) > 0;
        %Ov = (NODES{30,2}(end) - NODES{30,2}(1)) > 0;

        % index to position conversion is then determined by orientation


        Nhmin = NODES{02,ibox}(1);
        Nhmax = NODES{02,ibox}(2);
        Nvmin = NODES{02,ibox}(3);
        Nvmax = NODES{02,ibox}(4);




        % horizontal line x index
        indxh = (Nhmin-proxy_layer):(Nhmax+proxy_layer);
        lenx = length(indxh);
        indxh = repmat(indxh,proxy_layer,1);
        % vertical line y index
        if level > (xcutnum + 1) % surrounding proxy surface
            indyv = Nvmin:Nvmax;
            leny = length(indyv);
            indyv = repmat(indyv,proxy_layer,1);
        elseif level <= (xcutnum + 1) % vertical line sticking out proxy surface, vertical proxy surface
            indyv = (Nvmin-outnum):(Nvmax+outnum);
            leny = length(indyv);
            indyv = repmat(indyv,proxy_layer,1);
        end

        % horizontal line y index
            % line above
        indyh_up = (Nvmax+1:(Nvmax+1 + proxy_layer - 1))';
        indyh_up = repmat(indyh_up,1,lenx); 
            % line below
        indyh_down = ((Nvmin-1 -proxy_layer +1):Nvmin-1)';
        indyh_down = repmat(indyh_down,1,lenx);


        % vertical line x index
            % left line
        indxv_left = (Nhmin-1 - proxy_layer +1):Nhmin-1;
        indxv_left = repmat(indxv_left,leny,1)';
            % right line
        indxv_right = Nhmax+1:(Nhmax+1 + proxy_layer  - 1);
        indxv_right = repmat(indxv_right,leny,1)';

        %[top;down;left;right], add imaginary part to y coordinates
        indxh = indxh(:);
        indxv_left = indxv_left(:);
        indxv_right = indxv_right(:);

        if level > (xcutnum + 1)
            if Oh == 1 % list of hori coordinates is in increasing order
                xp = ([indxh;indxh;indxv_left;indxv_right]-1)*h;
            elseif Oh == -1 % list of hori coordinates is in decreasing order
                xp = (Nh-[indxh;indxh;indxv_left;indxv_right])*h;
            else
                error('Horizontal orientation invalid.');
            end
        elseif level <= (xcutnum + 1)
            if Oh == 1 % list of hori coordinates is in increasing order
                xp = ([indxv_left;indxv_right]-1)*h;
            elseif Oh == -1 % list of hori coordinates is in decreasing order
                xp = (Nh-[indxv_left;indxv_right])*h;
            else
                error('Horizontal orientation invalid.');
            end
        end

        indyv = indyv(:);
        indyh_up = indyh_up(:);
        indyh_down = indyh_down(:);


        if level > (xcutnum + 1)
            if Ov == 1 % list of vertical coordinates is in increasing order
                yp = ([indyh_up;indyh_down;indyv;indyv]-1)*h;
            elseif Ov == -1 % list of vertical coordinates is in decreasing order
                yp = (Nv-([indyh_up;indyh_down;indyv;indyv]))*(h);
            else
                error('Horizontal orientation invalid.');
            end
        elseif level <= (xcutnum + 1)
            if Ov == 1 % list of vertical coordinates is in increasing order
                yp = ([indyv;indyv]-1)*h;
            elseif Ov == -1 % list of vertical coordinates is in decreasing order
                yp = (Nv-([indyv;indyv]))*(h);
            else
                error('Horizontal orientation invalid.');
            end
        end


        NODES{13,ibox} = xp;  %x coordinates of proxy surface
        NODES{14,ibox} = yp;  %y coordinates of proxy surface, y cooridnates


        % figure;
        % hold on;
        % plot(NODES{06,ibox}+1i*NODES{07,ibox},'o');
        % % proxy points
        % plot(xp+1i*yp,'*');
        % hold off;
    end
    end

end